chromadb:
  host: localhost
  port: 8001
collection: texas_senate_legislators

model:
  name: sentence-transformers/all-mpnet-base-v2

search:
  top_k: 3

data:
  raw_document_path: data/State_House_Reps.csv